import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync } from "node:fs";
import { join, dirname } from "node:path";

function atomicWrite(file, content) {
  const dir = dirname(file);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const tmp = `${file}.tmp.${Date.now()}.${Math.random().toString(36).slice(2, 8)}`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, file);
}

export function getLearningsPath(root = process.cwd()) {
  return join(root, ".agent", "knowledge", "learnings.json");
}

export function getSystemLearningsMdPath(root = process.cwd()) {
  return join(root, ".agent", "SYSTEM_LEARNINGS.md");
}

export function loadLearnings(root = process.cwd()) {
  const dbFile = getLearningsPath(root);
  if (!existsSync(dbFile)) return [];
  try {
    return JSON.parse(readFileSync(dbFile, "utf8"));
  } catch (_) {
    return [];
  }
}

export function recordLearning(root = process.cwd(), learning = {}) {
  const { agent = "agent", trigger, solution, category = "GENERAL" } = learning;
  if (!trigger || !solution) {
    throw new Error("Trigger and solution are required to record a learning.");
  }

  const dbFile = getLearningsPath(root);
  const mdFile = getSystemLearningsMdPath(root);
  const db = loadLearnings(root);

  const cleanTrigger = trigger.trim();
  const cleanSolution = solution.trim();

  const isDuplicate = db.some(
    (l) =>
      l.trigger.toLowerCase() === cleanTrigger.toLowerCase() &&
      l.solution.toLowerCase() === cleanSolution.toLowerCase()
  );

  if (!isDuplicate) {
    db.push({
      date: new Date().toISOString().split("T")[0],
      agent,
      category,
      trigger: cleanTrigger,
      solution: cleanSolution,
    });
    atomicWrite(dbFile, JSON.stringify(db, null, 2));
  }

  // Render Markdown table
  const sanitize = (str) => str.replace(/\|/g, "&#124;").replace(/\r?\n/g, "<br>");
  let md = `<!-- 🚫 AUTO-GENERATED. AGENTS: DO NOT EDIT THIS FILE DIRECTLY. -->\n`;
  md += `# 🧠 System Learnings & Platform Quirks\n\n`;
  md += `> **⚠️ TO AGENTS:** NEVER edit this file manually. Record learnings via:\n`;
  md += `> \`agentctl learning add "<trigger>" "<solution>"\`\n\n`;
  md += `| Date | Agent | Trigger / Symptom | Mandatory Rule / Solution |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;

  db.forEach((l) => {
    md += `| ${l.date} | \`${l.agent}\` | ${sanitize(l.trigger)} | **${sanitize(l.solution)}** |\n`;
  });

  atomicWrite(mdFile, md);
  return { recorded: !isDuplicate, count: db.length };
}

export function hydratePrompt(root = process.cwd(), promptText = "", opts = {}) {
  const max = opts.max || 5;
  const learnings = loadLearnings(root);
  if (learnings.length === 0) return promptText;

  const lowerPrompt = promptText.toLowerCase();
  const matched = learnings.filter((l) => {
    const triggerWords = l.trigger.toLowerCase().split(/\s+/).filter((w) => w.length > 3);
    return triggerWords.some((w) => lowerPrompt.includes(w));
  }).slice(0, max);

  const activeLearnings = matched.length > 0 ? matched : learnings.slice(-max);

  let header = "\n\n<ACTIVE_SYSTEM_LEARNINGS>\n";
  header += "The following platform quirks & resolution rules apply to this task:\n";
  activeLearnings.forEach((l) => {
    header += `- [${l.category || "RULE"}] WHEN: ${l.trigger} → THEN: ${l.solution}\n`;
  });
  header += "</ACTIVE_SYSTEM_LEARNINGS>\n";

  // Check for baton pass state
  const batonFile = join(root, ".agent", "state", "baton_pass.json");
  let batonBlock = "";
  if (existsSync(batonFile)) {
    try {
      const baton = JSON.parse(readFileSync(batonFile, "utf8"));
      batonBlock = `\n<BATON_PASS_STATE>\n`;
      batonBlock += `Previous Task ID: ${baton.taskId || "unknown"}\n`;
      batonBlock += `Last Status: ${baton.status || "BLOCKED"}\n`;
      if (baton.summary) batonBlock += `Summary: ${baton.summary}\n`;
      batonBlock += `</BATON_PASS_STATE>\n`;
    } catch (_) {}
  }

  return `${header}${batonBlock}\n${promptText}`;
}

export function harvestFailure(root = process.cwd(), opts = {}) {
  const { exitCode = 4, logPath, diffText = "", taskId = "unknown", agent = "jules" } = opts;

  let logContent = "";
  if (logPath && existsSync(logPath)) {
    try {
      logContent = readFileSync(logPath, "utf8");
    } catch (_) {}
  }

  // Guard: Test Weakening check
  const testWeakeningRegex = /-\s*(it\(|test\(|expect\(|assert\.)/g;
  if (testWeakeningRegex.test(diffText)) {
    return { status: "REJECTED", reason: "TEST_WEAKENING: Attempted to delete or weaken test assertions." };
  }

  // Guard: Diff Limit check (75 KiB limit)
  const MAX_DIFF_BYTES = 75 * 1024;
  if (Buffer.byteLength(diffText, "utf8") > MAX_DIFF_BYTES) {
    return { status: "REJECTED", reason: "DIFF_PAYLOAD_LIMIT: Diff payload exceeds 75 KiB limit." };
  }

  // Extract error trace line
  const errorLine = logContent.split("\n").find((line) => /Error:|FAIL|TypeError|AssertionError/.test(line)) || "Unknown execution failure";

  const candidate = {
    agent,
    category: "OODA_HARVEST",
    trigger: `[OODA Exit ${exitCode}] ${errorLine.slice(0, 120)}`,
    solution: `Verify root cause from log (Task ${taskId}) before altering logic. Avoid fragile hacks or removing assertions.`,
  };

  const res = recordLearning(root, candidate);
  return { status: "HARVESTED", candidate, recorded: res.recorded };
}
